### ISSUE TITLE
Post : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by divick** [aertje/cloud-tasks-emulator#25] opened 2021-01-25 19:04 UTC
My issue is quite similar to issue #24 and I am using code quite similar to that in the issue #24 except I am not using any app_engine_routing. And I am getting this error.

For some reason on app engine standard environment, I am getting error when create_task is called, with specific error being that url is not present the the request even though I __am__ specifying the relative_uri.

I thought I might be able to quickly test my cloud task locally using your cloud-task-emulator, but apparently I run into some other issue altogether.

**Comment by aertje** [comment] 2021-01-25 23:38
Hi @divick, any chance you specified `APP_ENGINE_EMULATOR_HOST` to be e.g. `localhost:8000` instead of `http://localhost:8080` ?

**Comment by divick** [comment] 2021-01-26 02:24
No I specified it to be http://

**Comment by JeanDaniel-Fischer** [comment] 2021-02-25 17:09
Hi,

I am having the same issue in the Java 11 environment but I think the source is that I am using the AppEngineHttpRequest builder when I am creating the task on my local environment. The problem is that in your local environment, your code does not know the base url of your App Engine as you are not running in App Engine then the uri result in something like this one with no scheme : example.appspot.com/api/myrest/path.

My workaround is to use the HttpRequest builder for my task in local so I can set a full URL with the scheme.

I hope it can help you or other.

**Comment by aertje** [comment] 2021-03-22 09:59
Hi @divick, @JeanDaniel-Fischer  - I'm still not able to reproduce this behaviour; Would you mind providing the command you used and output of your client when you add the task, it will make it easier to understand how you are using it e.g. in python it returns something like this:

```
name: "/projects/my-sandbox/locations/us-central1/queues/test/tasks/8674665223082153551"
app_engine_http_request {
  http_method: POST
  app_engine_routing {
    host: "https://my-sandbox.appspot.com"
  }
  relative_uri: "/stuff"
  headers {
    key: "User-Agent"
    value: "AppEngine-Google; (+http://code.google.com/appengine)"
  }
}
schedule_time {
  seconds: 1616325466
  nanos: 238310295
}
create_time {
  seconds: 1616325466
}
dispatch_deadline {
  seconds: 600
}
view: BASIC
```

Thanks

**Comment by aertje** [comment] 2021-05-29 07:16
Closing as no more details of how to reproduce have been provided.

**Closed by aertje** 2021-05-29 07:16 UTC
Labels: bug, question
