### ISSUE TITLE
Malformed queue name raises panic during parseTaskName

### ISSUE THREAD

**Issue by szelenka** [aertje/cloud-tasks-emulator#32] opened 2021-04-14 13:48 UTC
Using the docker image here `ghcr.io/aertje/cloud-tasks-emulator:master` and following the Python examples, we're able to call `create_queue` with a malformed name, but when we attempt to `create_task` to that same queue, it'll raise a panic:
```
panic: runtime error: index out of range [1] with length 0
goroutine 44 [running]:
main.parseTaskName(0xc000168200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/app/task.go:34 +0x16e
main.dispatch(0xc000168201, 0xc000168200, 0x0)
/app/task.go:328 +0x3ee
main.(*Task).doDispatch(0xc000066700, 0xc0004ce001)
/app/task.go:349 +0x38
main.(*Task).Attempt(0xc000066700)
/app/task.go:359 +0x3e
main.(*Queue).runWorker(0xc0001bea80)
/app/queue.go:127 +0x3f
created by main.(*Queue).runWorkers
/app/queue.go:119 +0x48
```

In this specific case, the queue name had an underscore  in the name, which is not a valid URI character. Replacing underscore with a hyphen in the queue name mitigated this panic. This follows the pattern outlined by the spec:
https://cloud.google.com/tasks/docs/reference/rpc/google.cloud.tasks.v2beta3#google.cloud.tasks.v2beta3.Queue

Oddly, it was able to return the call back to Python without any issues. It's only on subsequent `create_task` calls that we noticed the docker image had crashed.

It'd be nice to return some error to the caller when/if they attempt to `create_queue` or `create_task` with an illegal character in the queue name.

**Comment by aertje** [comment] 2021-04-23 23:00
Hi @szelenka - thanks for reporting. I tried to reproduce the problem by creating a queue with an underscore, but it does not allow me to do that:
```
import grpc
from google.cloud.tasks_v2 import CloudTasksClient
from google.cloud.tasks_v2.services.cloud_tasks.transports import CloudTasksGrpcTransport

channel = grpc.insecure_channel('localhost:8123')

# Before v2.0.0 of the client
# client = CloudTasksClient(channel=channel)

transport = CloudTasksGrpcTransport(channel=channel)
client = CloudTasksClient(transport=transport)

parent = '/projects/my-sandbox/locations/us-central1'
**queue_name = parent + '/queues/test_ing'**
client.create_queue(queue={'name': queue_name}, parent=parent)
```
immediately returns:
```
Traceback (most recent call last):
  File "/home/aert/.venvs/cloud-tasks-emulator/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/aert/.venvs/cloud-tasks-emulator/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/aert/.venvs/cloud-tasks-emulator/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Queue name must be formatted: "projects/<PROJECT_ID>/locations/<LOCATION_ID>/queues/<QUEUE_ID>""
        debug_error_string = "{"created":"@1619218371.653003317","description":"Error received from peer ipv4:127.0.0.1:8123","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Queue name must be formatted: "projects/<PROJECT_ID>/locations/<LOCATION_ID>/queues/<QUEUE_ID>"","grpc_status":3}"
```

I think the fact that the error shows a "index out of range" might indicate that the queue wasn't created (as per this example) but that error returned was ignored by the client. Obviously it should still not have resulted in a panic though, so I'll look into that.
The fact that it returns the call to the client fine while it is actually causing a problem is not unexpected: the traceback you provided shows that the problem is picked up in the worker, which runs asynchronously from the grpc call.

**Comment by aertje** [comment] 2021-05-29 07:18
Closing as not able to reproduce and no further details provided.

**Closed by aertje** 2021-05-29 07:18 UTC
Labels: bug, question

**Comment by a7medkamel** [comment] 2025-07-26 13:46
I reproed the same issue with a name like `Q_VIDEO`
